version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      angular:
        patterns:
          - "@angular/*"
        update-types:
          - minor
          - patch
  - package-ecosystem: npm
    directory: /kits/react/template
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
  - package-ecosystem: npm
    directory: /kits/angular/template
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    groups:
      angular-kit:
        patterns:
          - "@angular/*"
          - "ng-packagr"
          - "typescript"
        update-types:
          - minor
          - patch
